--- 1) the-pads

SELECT CONCAT(NAME, '(', LEFT(OCCUPATION,1), ')')
FROM OCCUPATIONS
ORDER BY NAME;

SELECT CONCAT('There are a total of ', CNT, ' ', L_OCCUPATION, 's.')
FROM (
SELECT LOWER(OCCUPATION) AS L_OCCUPATION, COUNT(*) AS CNT
FROM OCCUPATIONS
GROUP BY LOWER(OCCUPATION)
) A 
ORDER BY CNT, L_OCCUPATION;

--- 2) OCCUPATIONS


